name: catbreeds
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  dio: ^5.7.0
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.5.1
  shared_preferences: ^2.3.2
  go_router: ^14.2.8
  flutter_svg: ^2.0.10+1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
      - .env
      - assets/icons/
      - assets/images/
      - assets/gifs/