name: catbreeds
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_native_splash: ^2.4.3
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.10+1
  go_router: ^14.2.8
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#e7dfdd"
  image: assets/images/splash_image.png
  branding: assets/images/branding.png
  android: true
  ios: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 24

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icons/
    - assets/images/
    - assets/gifs/
    - assets/
  
  fonts:
    - family: Gotham
      fonts:
        - asset: assets/fonts/gotham/GothamBold.ttf
          weight: 700
        #w600 no se usa en el proyecto
        - asset: assets/fonts/gotham/GothamMedium.ttf
          weight: 600
        - asset: assets/fonts/gotham/GothamMedium.ttf
          weight: 500
        - asset: assets/fonts/gotham/GothamBook.ttf
          weight: 400
        #w300 no se usa en el proyecto
        - asset: assets/fonts/gotham/GothamLight.ttf
          weight: 300
    - family: Gotham3
      fonts:
        - asset: assets/fonts/gotham3/GothamBold.ttf
          weight: 700
        #w600 no se usa en el proyecto
        - asset: assets/fonts/gotham3/GothamMedium.ttf
          weight: 600
        - asset: assets/fonts/gotham3/GothamMedium.ttf
          weight: 500
        - asset: assets/fonts/gotham3/GothamLight.ttf
          weight: 400
        #w300 no se usa en el proyecto
        - asset: assets/fonts/gotham3/GothamLight.ttf
          weight: 300
